name: Draft Release

# Should run when push a new tag. See "events-cases.yml" for examples.
on:
  - workflow_dispatch

jobs:
  draft-release:
    name: Draft Release ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount Body
        id: mount_body
        run: git log --pretty=format:"%h - (%an) %s %n%b" --no-merges $((git describe --tags --abbrev=0 && echo ..) | sed '$!N; s/\n//')HEAD | awk 'NF' > CHANGES.txt

      - name: Create Release
        id: create_release # Optional if not referenced by another step.
        uses: actions/create-release@v1 # Warning: This actions is deprecated. See the repo for more details.
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGES.txt
          draft: true # Recommend always true, to validate the release manualy before publish it.
